### PR TITLE
Return errors instead of throwing

### PR DESCRIPTION
**Pull request by lucacorti**
So, this is a first stab at changing the interface of the `HPack` and `HPack.Table` public API to return `{:ok, result} | {:error, reason}` tuples instead of throwing.

As a bonus, it also adds an (optional) `max_size` argument to `HPack.decode` and `HPack.Table.resize`. This is needed because dynamic table size updates need to be bounded and the limit is maintained by the user of the decoder (in my case the HTTP/2 protocol). When the dynamic table size update exceeds `max_size` an error is returned.

I think there are probably cases where exceptions are generated by incomplete pattern matches on function heads, so it probably needs more work. Tests pass though, and a few initial tests with my HTTP/2 implementations look good.

This addresses #10

### CODE REVIEW

**Comment by lucacorti** [comment]
Second commit also converts the encode/decode functions to return errors.

**Comment by lucacorti** [comment]
Last commits also fix dynamic table size updates, which must appear at the beginning of the HBF as per HPACK spec point 4.2.

**Comment by lucacorti** [comment]
Hi @OleMchls, have you had a chance to review this?

**Comment by OleMchls** [comment]
Hey @lucacorti sorry for not responding. I actually like this change, however, this is a major breaking change. I will pull the changes give it a slight review and will publish a new major if everything is 👌

**Comment by OleMchls** [comment]
Merging this, as I like the change as stated. It will require a new major version.

In a perfect world, a new major would come with a changelog and stuff but reality shapes scope in this case. @lucacorti if you'd like to contribute any of those please feel free to do so in a follow up PR, you are also very much invited to add yourself to a not yet existing contributes section or file :)

**Comment by OleMchls** [comment]
These changes are included in https://hex.pm/packages/hpack/2.0.0

**Pull request merged**
